/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/daily-survey`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/screen-time-input`; params?: Router.UnknownInputParams; } | { pathname: `/screen-time-intro`; params?: Router.UnknownInputParams; } | { pathname: `/submitted`; params?: Router.UnknownInputParams; } | { pathname: `/weekly-survey`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/daily-survey`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/screen-time-input`; params?: Router.UnknownOutputParams; } | { pathname: `/screen-time-intro`; params?: Router.UnknownOutputParams; } | { pathname: `/submitted`; params?: Router.UnknownOutputParams; } | { pathname: `/weekly-survey`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/daily-survey${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/screen-time-input${`?${string}` | `#${string}` | ''}` | `/screen-time-intro${`?${string}` | `#${string}` | ''}` | `/submitted${`?${string}` | `#${string}` | ''}` | `/weekly-survey${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/daily-survey`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/screen-time-input`; params?: Router.UnknownInputParams; } | { pathname: `/screen-time-intro`; params?: Router.UnknownInputParams; } | { pathname: `/submitted`; params?: Router.UnknownInputParams; } | { pathname: `/weekly-survey`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
